library/catalog/urls.py
from django.urls import path
from catalog import views

# app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('book_create/', views.BookCreate.as_view(), name='book_create'),
    path('book_detail/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('my_view/', views.my_view, name='my_view'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('profile/', views.CheckedOutBooksByUser.as_view(), name='profile')
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

library/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

import uuid

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self) -> str:
        return f"{self.name}"

    
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(to='Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=600)
    isbn = models.CharField('ISBN', max_length=13, unique=True)
    genre = models.ManyToManyField(to=Genre)
    language = models.ForeignKey(to='Language', on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})
    


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})
    
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey(to='Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(to=User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
                    ('m', 'Maintenance'),
                    ('o', 'On Laon'),
                    ('a', 'Available'),
                    ('r', 'Reserved')
                  )
    
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m')
    class Meta:
        ordering = ['due_back']

    def __str__(self) -> str:
        return f"{self.id} ({self.book.title})"
    
class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name

library/catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from catalog.models import Book, BookInstance
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_available_instances = BookInstance.objects.filter(status__exact='a').count()

    context = {
                'num_books': num_books,
                'num_inst': num_instances,
                'num_avail_inst': num_available_instances
              }
    
    return render(request, 'catalog/index.html', context=context)


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = "__all__"

class BookDetail(DetailView):
    model = Book

@login_required
def my_view(request):
    return render(request, 'catalog/my_view.html')

class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'catalog/signup.html'
    success_url = reverse_lazy('login')

class CheckedOutBooksByUser(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user)
    
    def get_context_data(self):
        context = {'user': self.request.user}
        return context

library/catalog/templates/catalog/book_detail.html
<h1>The book is:</h1>
{{book}}

library/catalog/templates/catalog/book_form.html
<h1>Add a new Book:</h1>

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Create">
</form>

library/catalog/templates/catalog/index.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Index Page:</h1>
  <p>Total Books: {{num_books}}</p>
  <p>Total instances: {{num_inst}}</p>
  <p>Total available instances: {{num_avail_inst}}</p>
  {% if user.is_authenticated %}
    <p>You are logged in as {{user.get_username}}.</p>
    <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
  {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}?next={{request.path}}">Login</a>
  {% endif %}
</body>
</html>

library/catalog/templates/catalog/my_view.html
<h1>Logged in users only!</h1>

library/catalog/templates/catalog/profile.html
<h1>Welcome to your profile: {{user}}</h1>
<h2>Here are the books checked out:</h2>

{% for book in bookinstance_list  %}
  <p>{{book}}</p>
{% endfor %}

library/catalog/templates/catalog/signup.html
<h1>Register new user:</h1>

<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Signup">
</form>